//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDbEntitiesComplete : DbContext
    {
        public myDbEntitiesComplete()
            : base("name=myDbEntitiesComplete")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Hire> Hires { get; set; }
        public virtual DbSet<Outlet> Outlets { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
